In [22]:
# 객체의 이름, 전화번호, 이메일주소, 주소 데이터를 읽어와 데이터 추가 및 삭제,
# 출력 후 재저장할 수 있는 class

# 데이터 추가 : 정규화 식으로 각 데이터의 형식 유효성 판단
# 데이터 삭제 : 일부 데이터만으로 이를 포함한 객체 검색한 뒤 원하는 데이터 선택해 삭제

class PhoneBook:
    
    def __init__(self):
        global pd, re, display, HTML
        from IPython.display import display # 시리즈를 표 형태로 출력하기 위한 Lib
        import pandas as pd
        import re
        self.file=pd.read_csv('PhoneBook.txt')
        PhoneBook.action(self)
    
    # 메뉴 선택 기능############################################################
    def action(self):
        print('1. 연락처 입력\n2. 연락처 출력\n3. 연락처 삭제\n4.종료\n')
        self.act=input('메뉴 선택 :')
        if self.act=='1': PhoneBook.addInfo(self)
        elif self.act=='2': PhoneBook.printInfo(self)
        elif self.act=='3': PhoneBook.deleteInfo(self)
        elif self.act=='4': PhoneBook.end(self)
        else: 
            print('잘못 입력하셨습니다.')
            PhoneBook.action(self)
    
    #데이터 추가 기능############################################################
    def addInfo(self):
        self.name=input('이름 :')
        self.num=input('전화번호 :')
        self.mail=input('이메일 :')
        self.addr=input('주소 :')
        
        # 각 데이터의 정규식 정의
        form_name=re.match('\w{0,3}',self.name)
        form_num=re.match('\d{2,3}-\d{4}-\d{4}',self.num)
        form_mail=re.match('[\w\d_]+@\w+.\w*[.]\w+',self.mail)
        form_addr=re.match('[\w ]+',self.addr)
        print(any([form_name,form_num,form_mail,form_addr]))
        
        # 모두 형식에 맞게 입력되었는지 판단
        if not all([form_name,form_num,form_mail,form_addr]):
            print('잘못된 형식입니다. 다시 시도해 주세요')
            
        # 형식에 맞으면 기존 데이터에 추가
        else:
            self.info=pd.DataFrame([[self.name,self.num,self.mail,self.addr]],
                              columns=self.file.columns)
            self.file=self.file.append(self.info)
        
        PhoneBook.action(self)
    
    # 데이터 전체 출력 기능############################################################
    def printInfo(self):
        display(self.file)
        PhoneBook.action(self)
    
    # 삭제 원하는 데이터 정보 받아와 findData()로 삭제하는 기능####################
    def deleteInfo(self):
        print('삭제를 원하는 분의 정보를 검색합니다.\n알고 있는 정보를 선택하세요.\n')
        temp=input('1. 이름\n2. 전화번호\n3. 이메일\n4. 주소\n')
        if temp=='1':
            inp=input('이름 :')
            PhoneBook.findData(self,'이름',inp)
        elif temp=='2':
            inp=input('전화번호 :')
            PhoneBook.findData(self,'전화번호',inp)
        elif temp=='3':
            inp=input('이메일 :')
            PhoneBook.findData(self,'이메일',inp)
        elif temp=='4':
            inp=input('주소 :')
            PhoneBook.findData(self,'주소',inp)
        PhoneBook.action(self)
        
    # 삭제 원하는 데이터의 위치를 찾아 해당 열 삭제하는 기능####################
    def findData(self,col,inp): 
        cnt=1
        res=[]
        # 입력된 데이터와 일치하는 데이터 있는 행 인덱스 res에 저장
        for i in range(len(self.file[col])):
            if re.search(str(inp),str(self.file[col][i])):
                res.append(i)
                cnt+=1
                
        # 입력된 데이터와 일치하는 데이터가 없는 경우
        if cnt==1:
            print('해당하는 정보가 없습니다.')
            
        # 일치하는 모든 데이터 중 원하는 데이터 선택, 삭제
        else:
            display(self.file.iloc[res])
            delInfo=int(input('삭제를 원하는 데이터 번호를 입력하세요\n'))
            if delInfo in res: 
                self.file=self.file.drop(delInfo,axis=0)
                self.file.index=range(len(self.file))
                print('삭제되었습니다')
            else: print('잘못 입력하셨습니다. 다시 시도해주세요.')

    # 종료 기능############################################################
    def end(self):
        self.file.to_csv('PhoneBook.txt',index=False)
        print('세션을 종료합니다.')

In [23]:
PhoneBook()

1. 연락처 입력
2. 연락처 출력
3. 연락처 삭제
4.종료

메뉴 선택 :2

    이름            전화번호                  이메일  주소
0  홍길동   010-1234-5678    aaa0000@naver.com  일산
1  김나나   010-2345-8989     abcd@hanmail.net  강남
2  마블리   010-1119-1112   dsm0000@abc.ac.org  강동
3   돌쇠   011-2222-2345    hehe@annyeong.com  서울
4  스누피   031-8888-1234  snp1234@hello.world  미국

1. 연락처 입력
2. 연락처 출력
3. 연락처 삭제
4.종료

메뉴 선택 :3
삭제를 원하는 분의 정보를 검색합니다.
알고 있는 정보를 선택하세요.

1. 이름
2. 전화번호
3. 이메일
4. 주소
4
주소 :미국

    이름           전화번호                  이메일  주소
4  스누피  031-8888-1234  snp1234@hello.world  미국

삭제를 원하는 데이터 번호를 입력하세요
2
잘못 입력하셨습니다. 다시 시도해주세요.
1. 연락처 입력
2. 연락처 출력
3. 연락처 삭제
4.종료

메뉴 선택 :3
삭제를 원하는 분의 정보를 검색합니다.
알고 있는 정보를 선택하세요.

1. 이름
2. 전화번호
3. 이메일
4. 주소
4
주소 :미국

    이름           전화번호                  이메일  주소
4  스누피  031-8888-1234  snp1234@hello.world  미국

삭제를 원하는 데이터 번호를 입력하세요
4
1. 연락처 입력
2. 연락처 출력
3. 연락처 삭제
4.종료

메뉴 선택 :2

    이름            전화번호                 이메일  주소
0  홍길동   010-1234-5678   aaa0000@naver.com  일산
1  김나나   010-2345-8989    abcd@hanmail.net  강남
2  마블리   010-1119-1112  dsm0000@abc.ac.org  강동
3   돌쇠   011-2222-2345   hehe@annyeong.com  서울

1. 연락처 입력
2. 연락처 출력
3. 연락처 삭제
4.종료

메뉴 선택 :4
세션을 종료합니다.

In [6]:
if not any([None,False]):
    print(1)

1

In [ ]:
def findData(self,col,inp):
    cnt=1
    for i in range(len(self.file[col])):
            if str(self.file[col][i])==inp:
                    print(self.file[col][i])
                    print('<%d 번 데이터>' %cnt)
                    print(self.file.iloc[i])
                    cnt+=1
            delInfo=int(input('삭제를 원하는 데이터 번호를 입력하세요\n'))
            self.file=self.file.drop(delInfo,axis=0)
            pass

In [ ]:
def deleteInfo(self):
        print('삭제를 원하는 분의 정보를 검색합니다.\n알고 있는 정보를 선택하세요.\n')
        delInfo=input('1. 이름\n2. 전화번호\n3. 이메일\n4. 주소\n')
        res=[]
        if delInfo=='1':
            self.name=input('이름 :')
            cnt=1
            for i in range(len(self.file['이름'])):

                if str(self.file['이름'][i])==self.name:
                    print(self.file['이름'][i])
                    print('<%d 번 데이터>' %cnt)
                    print(self.file.iloc[i])
                    res.append(i)
                    cnt+=1
            delInfo=int(input('삭제를 원하는 데이터 번호를 입력하세요\n'))
            self.file=self.file.drop(delInfo,axis=0)
            pass
        elif delInfo=='2':
            self.name=input('이름 :')
            cnt=1
            for i in range(len(self.file['이름'])):
                print(self.file['이름'][i])
                if str(self.file['이름'][i])==self.name:
                    print(self.file['이름'][i])
                    print('<%d 번 데이터>' %cnt)
                    print(self.file.iloc[i])
                    res.append(i)
                    cnt+=1
            delInfo=int(input('삭제를 원하는 데이터 번호를 입력하세요\n'))
            self.file=self.file.drop(delInfo,axis=0)
            pass
            
        elif delInfo=='3':
            print('이메일 :')
            
        elif delInfo=='4':
            print('주소 :')
            
        else:
            print('잘못 입력하셨습니다.')
            PhoneBook.deleteInfo(self)
        PhoneBook.action(self)